import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";

import Navbar from "./component/Navbar/Navbar";
import Sidebar from "./component/Sidebar/Sidebar";
import { routes } from "./component/Navbar/Routes";
import { sidebarRoutes } from "./component/Sidebar/Routes";
import { Suspense } from "react";
import Loading from "./loading";

const font = Quicksand({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "QualifAI",
  description: "Generated by SimplifAI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <ThemeProvider>
          <Navbar routes={routes} />
          <div className="flex">
            <Sidebar routes={sidebarRoutes} />
            <main className="flex-1 relative ml-0 md:ml-64 p-4">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
