import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";

import Navbar from "../components/Navbar/Navbar";
import { routes } from "../components/Navbar/Routes";
import { sidebarRoutes } from "../components/Sidebar/Routes";
import ClientLayout from "./clientWrapper";
import { AuthProvider } from "../context/AuthContext";
import { LayoutProvider } from "../context/LayoutContext"; // Now this exists

const font = Quicksand({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "QualifAI",
  description: "Generated by SimplifAI",
};

// Create a client wrapper that uses auth to provide layout context
function AuthLayoutWrapper({
  children,
  sidebarRoutes,
}: {
  children: React.ReactNode;
  sidebarRoutes: any[];
}) {
  return (
    <ClientLayout sidebarRoutes={sidebarRoutes}>
      <main className="min-h-screen pt-16">{children}</main>
    </ClientLayout>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <AuthProvider>
          <ThemeProvider>
            {/* Wrap with LayoutProvider */}
            <LayoutProvider>
              <Navbar routes={routes} />
              <AuthLayoutWrapper sidebarRoutes={sidebarRoutes}>
                {children}
              </AuthLayoutWrapper>
            </LayoutProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
