import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";

import Navbar from "../components/Navbar/Navbar";
import Sidebar from "../components/Sidebar/Sidebar";
import { routes } from "../components/Navbar/Routes";
import { sidebarRoutes } from "../components/Sidebar/Routes";
import { Suspense } from "react";
import Loading from "./loading";
import ClientLayout from "./clientWrapper";

const font = Quicksand({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "QualifAI",
  description: "Generated by SimplifAI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <ThemeProvider>
          <Navbar routes={routes} />
          <ClientLayout sidebarRoutes={sidebarRoutes}>
            {children}
          </ClientLayout>{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
